site_name: Pydentity
nav:
  - Home:
    - Getting Started: index.md
    - Access Control: access.md
    - Contracts: contracts.md
    - Content: content.md
    - Contacts: contacts.md
    - Guard: guard.md
    - Control(ler): control.md
    - Persistence: persistence.md
    - Contributions: contributions.md
  - API:
    - Contracts: api/contracts.md
theme:
  name: material
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.footer
  palette:
    primary: navy
    accent: deep-orange
    scheme: dark
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
  - pymdownx.superfences
  - pymdownx.magiclink
  - pymdownx.emoji
  - pymdownx.snippets
  - pymdownx.inlinehilite
plugins:
  - tags
